"""Validate task JSON against reachable Three.js/GLB interaction targets."""

import json
import re
import struct
import sys
from pathlib import Path

APP_DIR = Path(__file__).resolve().parents[1]
HTML_PATH = APP_DIR / "ui" / "tutorial_3d.html"
TASK_FILES = {
    "biology": APP_DIR / "tasks_kidney.json",
    "chemistry": APP_DIR / "tasks_chemistry.json",
    "physics": APP_DIR / "tasks_physics.json",
}


def glb_node_names(path):
    data = path.read_bytes()
    if data[:4] != b"glTF":
        raise ValueError(f"Not a binary GLB: {path}")
    offset = 12
    while offset + 8 <= len(data):
        length, kind = struct.unpack_from("<II", data, offset)
        payload = data[offset + 8: offset + 8 + length]
        if kind == 0x4E4F534A:
            document = json.loads(payload.rstrip(b" \x00").decode("utf-8"))
            return {node.get("name") for node in document.get("nodes", []) if node.get("name")}
        offset += 8 + length
    raise ValueError(f"No JSON chunk in {path}")


def procedural_targets(html):
    names = set(re.findall(r"namedMesh\(\s*['\"]([^'\"]+)", html))
    names.update(re.findall(r"\.name\s*=\s*['\"]([^'\"]+)", html))
    names.update(re.findall(r"interactionTarget\s*=\s*['\"]([^'\"]+)", html))
    # Gear_1..4 are generated by a loop.
    names.update({f"Gear_{number}" for number in range(1, 5)})
    return names


def effective_targets(task, subject):
    targets = list(task.get("expected_targets") or [])
    if targets or task.get("type") != "gesture_task":
        return targets
    # Parse the authoritative pre-hardware mapping from task_engine by
    # importing it, rather than duplicating a second mapping in this tool.
    sys.path.insert(0, str(APP_DIR))
    from task_engine import PRE_HARDWARE_TARGETS
    return list(PRE_HARDWARE_TARGETS.get(task.get("task_id"), []))


def validate():
    html = HTML_PATH.read_text(encoding="utf-8")
    procedural = procedural_targets(html)
    biology_glb = APP_DIR / "ui" / "static" / "models" / "Biology_Kidney_Lab_Table.glb"
    subject_targets = {
        "biology": glb_node_names(biology_glb) | {"Scalpel"},
        "chemistry": procedural,
        "physics": procedural,
    }
    errors = []
    checked = 0
    for subject, path in TASK_FILES.items():
        payload = json.loads(path.read_text(encoding="utf-8"))
        tasks = [task for segment in payload.get("segments", []) for task in segment.get("tasks", [])]
        for task in tasks:
            checked += 1
            if task.get("type") == "numeric_question":
                if "expected_numeric_answer" not in task:
                    errors.append(f"{task['task_id']}: numeric task has no expected answer")
                if float(task.get("numeric_tolerance", 0)) <= 0:
                    errors.append(f"{task['task_id']}: numeric task needs positive tolerance")
            targets = effective_targets(task, subject)
            if task.get("type") == "gesture_task" and not targets:
                errors.append(f"{task['task_id']}: gesture task has no achievable target")
            available = subject_targets[subject]
            for target in targets:
                if not any(name == target or name.startswith(target + ".") for name in available):
                    errors.append(f"{task['task_id']}: missing scene target {target!r}")
            video = task.get("mini_tutorial_video")
            if video and not (APP_DIR / "ui" / video).exists():
                errors.append(f"{task['task_id']}: missing mini tutorial {video!r}")
    return checked, errors


if __name__ == "__main__":
    count, failures = validate()
    if failures:
        print(f"TARGET VALIDATION FAILED ({len(failures)} issues across {count} tasks)")
        print("\n".join(f"- {failure}" for failure in failures))
        raise SystemExit(1)
    print(f"TARGET VALIDATION OK: {count} tasks have reachable targets/assets")
